server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hm_dianping?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lf_MySQL
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    host: 192.168.252.130
    port: 6379
    password: 123321
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    listener:
      simple:
        prefetch: 1 # 每次只能从消息队列中取出1条消息
        acknowledge-mode: manual # 设置手动确认
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
logging:
  level:
    com.hmdp: debug
